# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor npm dependencies - Regular updates (daily)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "getgrowly"
    assignees:
      - "getgrowly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates together to reduce PR noise
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Allow updates for these types
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for these stable packages (review manually)
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "electron"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies - Security updates only
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 20
    reviewers:
      - "getgrowly"
    assignees:
      - "getgrowly"
    commit-message:
      prefix: "chore(deps-security)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"
      - "auto-merge"
    # Only security updates
    open-pull-requests-limit: 20

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "getgrowly"
    assignees:
      - "getgrowly"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
      - "automated"
      - "auto-merge"
