import { FlatCompat } from "@eslint/eslintrc"
import js from "@eslint/js"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
})

export default [
  // Ignore patterns
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/out/**",
      "**/dist/**",
      "**/build/**",
      "**/release/**",
      "**/coverage/**",
      "**/.vitest/**",
      "**/electron/dist/**",
      "**/next-env.d.ts", // Generated by Next.js
    ],
  },

  // Extend Next.js configs using FlatCompat
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  // Prettier compatibility
  ...compat.extends("prettier"),

  // Custom rules
  {
    rules: {
      // TypeScript specific rules
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "warn",

      // React specific rules
      "react/display-name": "warn",

      // General code quality
      "no-console": "off", // Allow console for debugging
      "no-debugger": "error",
      "no-var": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "warn",
      "prefer-template": "warn",
      eqeqeq: ["error", "always"],
      curly: ["error", "all"],

      // Best practices
      "no-duplicate-imports": "error",
      "no-unused-expressions": "error",
      "no-nested-ternary": "warn",
    },
  },

  // Test files overrides
  {
    files: ["**/__tests__/**/*", "**/*.test.*", "**/*.spec.*"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
]
